version: "3.4"

services:
  api:    
    container_name: household.buget
    image: household.buget
    build:
      context: ./src/Household.Budget
      dockerfile: Dockerfile
    ports:
      - 5215:80
      - 7086:443
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNET_ENV}
      - ASPNETCORE_URLS=http://+:80
      - Seed__Categories__Enabled=true
    depends_on:
      mongo:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/hc/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 2s
    command: sh -c 'exit 0'
  
  mongo:
    image: mongo
    container_name: ${PREFIX_CONTAINERS}.mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    cpus: 0.5
    mem_limit: 256M
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 40s
      
  rabbit:
    image: rabbitmq:3-management
    container_name: ${PREFIX_CONTAINERS}.rabbit
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      retries: 3
      start_period: 5s
