version: "3.4"

services:
  api:    
    container_name: household.buget
    image: household.buget
    build:
      context: ./src/Household.Budget
      dockerfile: Dockerfile
    ports:
      - 5215:80
      - 7086:443
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNET_ENV}
      - ASPNETCORE_URLS=http://+:80
      - Seed__Categories__Enabled=true
    depends_on:
      mongo:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/hc/live"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 2s