name: Continous Integration

on:
  push:
    branches:
      - "main"
      - "release/**"
      - "feature/**"

jobs:
  Versioning:
    name: Versioning
    uses: ./.github/workflows/git.yaml        

  building:
    name: Building application
    uses: ./.github/workflows/build.yaml
    needs: Versioning
    with:
      dotnet-version: "8.0.x"
      solution-name: household.buget.sln

