name: Continous Integration

on:
  push:
    branches:
      - "main"
      - "release/**"
      - "feature/**"

jobs:
  versioning:
    uses: ./.github/workflows/git.yaml

  testversion:
    name: Teste version
    runs-on: ubuntu-latest
    needs: Versioning
    steps:
      - run: echo version: ${{ needs.versioning.outputs.version }}

  # build:
  #   name: .Net Building
  #   uses: ./.github/workflows/build.yaml
  #   needs: Versioning
  #   with:
  #     dotnet-version: "8.0.x"
  #     solution-name: household.buget.sln

  # docker:
  #   name: Docker Build and publish
  #   uses: ./.github/workflows/docker.yaml
  #   # needs: build
  #   with:
  #     username: leandroalves86
  #     context: ./src/Household.Budget/
  #     dockerfile: ./src/Household.Budget/Dockerfile
  #     version: ${{ needs.versioning.outputs.version }}
  #     solution-name: household.buget
  #   secrets:
  #     usertoken: ${{ secrets.DOCKERHUB_TOKEN }}
