name: "Create Tag"

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string 

jobs:
  tag:
    name: "Create Tag ${{inputs.version}}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push Tag
        id: push-tag
        run: |
          tag="${{ inputs.version }}"
          echo $tag

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git tag $tag
          git push origin $tag