name: Dockerizing application

on:
  workflow_call:
    inputs:
      context:
        type: string
        default: "."
      dockerfile:
        type: string
        default: Dockerfile
      username:
        type: string
        required: true
      usertoken:
        type: string
        required: true
      solution-name:
        type: string
        required: true
        description: Solution name
      version:
        type: string
        default: latest
    secrets:
      usertoken:
        required: true        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.username }}
          password: ${{ secrets.usertoken }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ inputs.username }}/${{ inputs.solution-name}}:${{ inputs.version }}
