name: Git Version

on:
  workflow_call:
    inputs:
      gitversion-app:
        type: string
        required: false
        default: "5.12.0"   
    outputs:
      version: 
        description: Calculated application version
        value: ${{ jobs.versioning.outputs.version }}
      build:
        description: Build metadata paddded
        value: ${{ jobs.versioning.outputs.build }}

jobs:
  versioning:
    name: Git Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.SemVer }}
      build: ${{ steps.gitversion.outputs.BuildMetaDataPadded }}

    steps:
      - name: Downloading code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Installing GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: ${{ inputs.gitversion-app }}

      - name: Determining version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
