name: Git Version

on:
  workflow_call:
    inputs:
      gitversion-app:
        type: string
        required: false
        default: "5.12.0"   

jobs:
  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_output.outputs.fullSemVer }}

    steps:
      - name: Downloading code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: ${{ inputs.gitversion-app }}

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Setting outputs
        id: set_output
        run: |
          echo "version=$(dotnet-gitversion /showvariable fullsemver)" >> $GITHUB_OUTPUT
