name: Git Version

on:
  workflow_call:
    inputs:
      gitversion-app:
        type: string
        required: false
        default: "5.12.0"   
    outputs:
      version: 
        description: Calculated application version
        value: ${{ jobs.versioning.full_semver }}

jobs:
  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    outputs:
      full_semver: ${{ steps.set_version.outputs.fullsemver }}

    steps:
      - name: Downloading code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Installing GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: ${{ inputs.gitversion-app }}

      - name: Determining version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0

      - name: Setting version
        id: set_version
        run: echo "fullsemver=1.0.0-beta.1+13" >> "$GITHUB_OUTPUT"
