name: Git Version

on:
  workflow_call:

jobs:
  checkout:
    name: Git checkout
    runs-on: ubuntu-latest

    steps:
      - name: Fetching code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    outputs:
      fullsemver: ${{ steps.gitversion.outputs.fullSemVer }}

    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: "5.x"

      - name: Determine version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
