name: Continous Integration

on:
  push:
    branches:
      - "release/**"
      - "feature/**"
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  # versioning:
  #   uses: ./.github/workflows/git-version.yaml

  # build:
  #   uses: ./.github/workflows/build-net.yaml
  #   needs: Versioning
  #   with:
  #     solution-name: household.buget.sln

  # docker:
  #   uses: ./.github/workflows/docker-build-publish.yaml
  #   needs: [versioning, build]
  #   with:
  #     username: leandroalves86
  #     context: ./src/Household.Budget/
  #     dockerfile: ./src/Household.Budget/Dockerfile
  #     version: ${{needs.versioning.outputs.version}}.${{needs.versioning.outputs.build}}
  #     solution-name: household.buget
  #     default-branch: release
  #   secrets:
  #     usertoken: ${{ secrets.DOCKERHUB_TOKEN }}

  # deploy:
  #   uses: ./.github/workflows/azure-deploy.yaml
  #   needs: [docker]
  #   with:
  #     appname: householdbudget
  #     docker-image: ${{ needs.docker.outputs.docker-image }}
  #   secrets:
  #     azure-deploy: ${{ secrets.AZURE_DEPLOY  }}

  # tag:
  #   uses: ./.github/workflows/create-tag.yaml
  #   needs: [versioning, deploy]
  #   with:
  #     version: ${{needs.versioning.outputs.version}}.${{needs.versioning.outputs.build}}


  allowed-branches:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo branch: ${{ github.event.ref }}
          echo main: ${{ github.ref == 'refs/heads/main'}} 
          echo branches: ${{ fromJSON("['refs/heads/release/**', 'refs/heads/hotfix', 'refs/heads/main']" }}

        #escrever um arquivo apartado e tentar implementar a lógica abaixo 
        # na sintaxe do git  
      - run: |
          current_branch=${{ github.event.ref }}
          allowed_branches="release|main|hotfix"
          if echo "$current_branch" | grep -E "$allowed_branches" >/dev/null; then
              echo "Branch is allowed."
          else
              echo "Branch is not allowed."
              exit 0
          fi
  temp:
    uses: ./.github/workflows/temp.yaml