name: Continous Integration

on:
  push:
    branches:
      - "release/**"
      - "feature/**"
      - main
  pull_request:
    types:
      - opened
      - closed
      - synchronize
    branches:
      - main

jobs:
  versioning:
    uses: ./.github/workflows/git-version.yaml

  build:
    uses: ./.github/workflows/build-net.yaml
    needs: Versioning
    with:
      solution-name: household.buget.sln

  docker:
    uses: ./.github/workflows/docker-build-publish.yaml
    needs: [versioning, build]
    with:
      username: leandroalves86
      context: ./src/Household.Budget/
      dockerfile: ./src/Household.Budget/Dockerfile
      version: ${{needs.versioning.outputs.version}}
      solution-name: household.buget
      prefix-allowed-branch: release
    secrets:
      usertoken: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy:
    uses: ./.github/workflows/azure-deploy.yaml
    needs: [docker]
    with:
      appname: householdbudget
      docker-image: ${{ needs.docker.outputs.docker-image }}
    secrets:
      azure-deploy: ${{ secrets.AZURE_DEPLOY  }}

  tag:
    uses: ./.github/workflows/create-tag.yaml
    needs: [versioning, deploy]
    with:
      version: ${{needs.versioning.outputs.version}}
